concentriq-manager/app/routes/login_routes.py
from app.config import GLOBAL_STATE

import os
from flask import (
    Blueprint, render_template, request, redirect, url_for, flash, render_template, jsonify
)
import win32cred
from ConcentriqSDK.concentriq_service import ConcentriqService

login = Blueprint('login', __name__)

@login.route("/login")
def index():
    password, email="",""
    try:
        # Get credential from windows credential with name "ConcentriqProd"
        email_win, password_win = get_credentials()
        if email_win:
            email = email_win
        if password_win:
            password = password_win
    except:
        pass

    try:
        # Try to get from os environment variable password and mail
        if not password:
            password = os.environ.get('CONCENTRIQ_PASSWORD', '')
        if not email:
            email = os.environ.get('CONCENTRIQ_EMAIL', '')
    except:
        pass
    
    return render_template(
        'login.html',
        email = email,
        password = password,
    )

@login.route("/get_login", methods=["POST"])
def get_login():
    email = request.form.get("email", "").strip()
    password = request.form.get("password", "").strip()
    endpoint = request.form.get("concentriq_env", "").strip()

    if not email or not password or not endpoint:
        flash("Missing required settings (email, password, endpoint).", "error")
        return redirect(url_for("login.index"))

    try:
        concentriq_service = ConcentriqService(
            endpoint=endpoint,
            email=email, 
            password=password,
            pac_url=GLOBAL_STATE.get('pac_url'))
        
    except Exception as e:
        err_str = str(e)
        if '"status":401' in err_str or "login_failed" in err_str:
            flash("The login information is incorrect (401).", "error")
        else:
            flash(f"Error creating client: {e}", "error")
        return redirect(url_for("login.index"))

    if concentriq_service.is_logged():
        GLOBAL_STATE['service'] = concentriq_service
        print("ConcentriqService stored in GLOBAL_STATE:", GLOBAL_STATE['service'])
    else:
        print("Login failed. Service not stored.")
        return redirect(url_for("login.index"))

    flash("Login successfully.", "success")
    return redirect(url_for("main.index"))

@login.route('/get_env_options', methods=['GET'])
def get_env_options():
    """Allows to get different options for environment from config."""
    env_dict = {}
    try:
        for env_name in GLOBAL_STATE.get('endpoints'):
            env_dict[env_name] = GLOBAL_STATE.get('endpoints').get(env_name)
        return jsonify(env_dict)
    except Exception as e:
        return jsonify({"error": "Failed to retrieve environment options"}), 500

def get_credentials():
    try:
        cred = win32cred.CredRead("ConcentriqProd", win32cred.CRED_TYPE_GENERIC)
        username = cred['UserName']
        password = cred['CredentialBlob'].decode('utf-8').replace('\x00', '').strip()
        return username, password
    except Exception as e:
        print(f"Error retrieving credentials: {e}")
        return "", ""

concentriq-manager/app/routes/orderviewonly.py
from app.config import GLOBAL_STATE

from flask import (
    Blueprint, render_template, redirect, url_for, render_template, request, flash
)

orderviewonly = Blueprint('orderviewonly', __name__)

@orderviewonly.route("/orderviewonly")
def index():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    metadata_fields = None
    
    return render_template(
        'orderviewonly_page.html',
        metadata_fields=metadata_fields
    )

@orderviewonly.route("/orderviewonly/updatetable", methods=["POST"])
def updatetable():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    repository_id = request.form.get("source_repository_id")
    valid_repo, repo_info = check_valid_repo(concentriq_service, repository_id)
    if not valid_repo:
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    # Get metadata fields
    metadata_fields = get_metadata_fields(concentriq_service, repository_id)

    # Filter metadata fields depending on pushed button, and fill table
    if request.method == 'POST':
        if request.form.get('loadImageField') == 'Load Image fields':
            filtered_metadata_fields = [metadata_field for metadata_field in metadata_fields if metadata_field.get('content_type') == 'image']
        elif  request.form.get('loadFolderField') == 'Load Folder Fields':
            filtered_metadata_fields = [metadata_field for metadata_field in metadata_fields if metadata_field.get('content_type') == 'folder']
        elif  request.form.get('loadImageSetField') == 'Load ImageSet Fields':
            filtered_metadata_fields = [metadata_field for metadata_field in metadata_fields if metadata_field.get('content_type') == 'imageSet']
        else:
            flash("error to load metadata fields.", "error")
            return render_template("orderviewonly.index")
    
    filtered_metadata_fields = sorted(filtered_metadata_fields, key=lambda x: x['order'])
    return render_template(
        'orderviewonly_page.html',
        repository_text=get_repository_text(repo_info),
        repository_id=repository_id,
        metadata_fields=filtered_metadata_fields
    )

@orderviewonly.route("/orderviewonly/esmOrderUpdate", methods=["POST"])
def esmOrderUpdate():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    repository_id = request.form.get("hiddenrepoid1")
    valid_repo, repo_info = check_valid_repo(concentriq_service, repository_id)
    if not valid_repo:
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    ## Update order of "eSM" containing fields to the end
    filters = {
        'imageSetId': [repository_id]
    }
    res = concentriq_service.client.get_metadata_fields(filters)
    end_order = len(res.get('fields')) + 1
    
    for field_ in res.get('fields'):
        if 'eSM' in field_.get('name'):
            res = update_imageset_properties(concentriq_service.client, repository_id, field_.get('id'), orderNumber=end_order)
            if res is None:
                print(f"!!! Error for field (id: {field_.get('id')} for imageset (id: {repository_id}) !!!")
                flash(f"!!! Error for field (id: {field_.get('id')} for imageset (id: {repository_id}) !!!", "error")
            else:
                print(f"Change to order ({end_order}) for: field (id: {field_.get('id')}) --- name: {field_.get('name')}")
    
    # Get metadata fields and filter by content_type
    metadata_fields = get_metadata_fields(concentriq_service, repository_id)
    filtered_metadata_fields = sorted(metadata_fields, key=lambda x: x['content_type'])
    
    return render_template(
        'orderviewonly_page.html',
        repository_text=get_repository_text(repo_info),
        repository_id=repository_id,
        metadata_fields=filtered_metadata_fields
    )

@orderviewonly.route("/orderviewonly/esmViewOnlyUpdate", methods=["POST"])
def esmViewOnlyUpdate():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    repository_id = request.form.get("hiddenrepoid2")
    valid_repo, repo_info = check_valid_repo(concentriq_service, repository_id)
    if not valid_repo:
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    # Update order of "eSM" containing fields to ViewOnly
    filters = {
        'imageSetId': [repository_id]
    }
    res = concentriq_service.client.get_metadata_fields(filters)
    
    for field_ in res.get('fields'):
        if 'eSM' in field_.get('name'):
            res = update_imageset_properties(concentriq_service.client, repository_id, field_.get('id'), viewOnly=True, study=False)
            if res is None:
                print(f"Error for field (id: {field_.get('id')} for imageset (id: {repository_id})")
                flash(f"Error for field (id: {field_.get('id')} for imageset (id: {repository_id})", "error")
            else:
                print(f"Change to view only for: field (id: {field_.get('id')}) --- name: {field_.get('name')}")

    # Get metadata fields and filter by content_type
    metadata_fields = get_metadata_fields(concentriq_service, repository_id)
    filtered_metadata_fields = sorted(metadata_fields, key=lambda x: x['content_type'])
    
    return render_template(
        'orderviewonly_page.html',
        repository_text=get_repository_text(repo_info),
        repository_id=repository_id,
        metadata_fields=filtered_metadata_fields
    )

@orderviewonly.route("/orderviewonly/UpdateViewOnly", methods=["POST"])
def UpdateViewOnly():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    data = request.json
    repository_id = data.get('repository_id')
    metadata_field_id = data.get('metadata_field_id')
    checkbox_checked = data.get('checkbox_checked')
    
    valid_repo, repo_info = check_valid_repo(concentriq_service, repository_id)
    if not valid_repo:
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    try:
        metadata_field_id = int(metadata_field_id)
    except Exception as e:
        flash(f"{metadata_field_id} Not convertable to integer. ({e})", "error")
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    # Update ViewOnly status according to checkbox
    res = update_imageset_properties(concentriq_service.client, repository_id, metadata_field_id, viewOnly=checkbox_checked, study=False)
    
    if res is None:
        print(f"Error for field (id: {metadata_field_id} for imageset (id: {repository_id})")
        flash(f"Error for field (id: {metadata_field_id} for imageset (id: {repository_id})", "error")
    else:
        print(f"Change to view only for: field (id: {metadata_field_id})")

    # Get metadata fields and filter by content_type
    metadata_fields = get_metadata_fields(concentriq_service, repository_id)
    
    return render_template(
        'orderviewonly_page.html',
        repository_text=get_repository_text(repo_info),
        repository_id=repository_id,
        metadata_fields=metadata_fields
    )

@orderviewonly.route("/orderviewonly/UpdateStudy", methods=["POST"])
def UpdateStudy():
    # If not logged, return to login page
    concentriq_service = GLOBAL_STATE['service']
    if concentriq_service is None:
        return redirect(url_for("login.index"))
    
    data = request.json
    repository_id = data.get('repository_id')
    metadata_field_id = data.get('metadata_field_id')
    checkbox_checked = data.get('checkbox_checked')
    
    valid_repo, repo_info = check_valid_repo(concentriq_service, repository_id)
    if not valid_repo:
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    try:
        metadata_field_id = int(metadata_field_id)
    except Exception as e:
        flash(f"{metadata_field_id} Not convertable to integer. ({e})", "error")
        return render_template(
            'orderviewonly_page.html',
            repository_id=repository_id,
        )
    
    # Update ViewOnly status according to checkbox
    res = update_imageset_properties(concentriq_service.client, repository_id, metadata_field_id, viewOnly=False, study=checkbox_checked)
    
    if res is None:
        print(f"Error for field (id: {metadata_field_id} for imageset (id: {repository_id})")
        flash(f"Error for field (id: {metadata_field_id} for imageset (id: {repository_id})", "error")
    else:
        print(f"Change to Study for: field (id: {metadata_field_id})")

    # Get metadata fields and filter by content_type
    metadata_fields = get_metadata_fields(concentriq_service, repository_id)
    
    return render_template(
        'orderviewonly_page.html',
        repository_text=get_repository_text(repo_info),
        repository_id=repository_id,
        metadata_fields=metadata_fields
    )

@orderviewonly.route("/orderviewonly/OrderTemplateUpdate", methods=["POST"])
def OrderTemplateUpdate():

concentriq-manager/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='styles/login.css') }}"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/labcorp.ico') }}"
    />
  </head>
  <body>
    <div class="container">
      <h1>Concentriq Manager Login</h1>
      <div>
        <form method="POST" action="{{ url_for('login.get_login') }}">
          <div class="row">
            <label>Concentriq Email:</label>
            <input
              type="email"
              id="email"
              name="email"
              value="{{ email }}"
              placeholder="Enter Your Email"
              autofocus=""
            />
          </div>
          <div class="row">
            <label>Concentriq API password:</label>
            <input
              type="password"
              id="pass"
              name="password"
              value="{{ password }}"
              placeholder="Enter Your API password"
            />
          </div>
          <div class="row">
            <label>Select environment</label>
            <select id="concentriq_env" name="concentriq_env">
              <option value="" disabled selected>Select Environment</option>
            </select>
          </div>
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %}
          <div class="flash-msg">
            {% for category, msg in messages %}
            <div class="{{ category }}">{{ msg }}</div>
            {% endfor %}
          </div>
          {% endif %} {% endwith %}
          <div class="base-button">
            <button>Login</button>
          </div>
        </form>
      </div>
    </div>

    <script>
      // function to retreive and create different env options
      function populateEnvOptions() {
        fetch("/get_env_options")
          .then((response) => response.json())
          .then((data) => {
            const select = document.getElementById("concentriq_env");
            for (const [key, value] of Object.entries(data)) {
              const option = document.createElement("option");
              option.value = value;
              option.text = key + ":" + value;
              if (key == "production") {
                option.selected = "selected";
              }
              select.appendChild(option);
            }
          });
      }

      // Function to run at opening of the page
      window.onload = function () {
        populateEnvOptions();
      };
    </script>
  </body>
</html>

concentriq-manager/app/templates/main_page.html
<!DOCTYPE html>
<html>
  <head>
    <title>MainPage</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='styles/main_page.css') }}"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/labcorp.ico') }}"
    />
  </head>
  <body>
    <div class="container">
      <h1 class="list-functionality">List of functionalities:</h1>
      <div class="base-button">
        <button
          class="base-button"
          onclick="window.location.href='/orderviewonly';"
        >
          Order&ViewOnly
        </button>
      </div>
      <div class="base-button">
        <button class="base-button" onclick="window.location.href='/ocr';">
          Fill Metadata
        </button>
      </div>
      <div class="base-button">
        <button class="base-button" onclick="window.location.href='/transfer';">
          Transfer
        </button>
      </div>
      <div class="base-button">
        <button class="base-button" onclick="window.location.href='/rename';">
          Rename Images
        </button>
      </div>
    </div>
  </body>
</html>

concentriq-manager/app/templates/orderviewonly_page.html
<!DOCTYPE html>
<html>
  <head>
    <title>Order&ViewOnly</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='styles/order.css') }}"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/labcorp.ico') }}"
    />
  </head>
  <body>
    <!--Title -->
    <h1>Change Order&ViewOnly for Metadata Fields</h1>
    <p>
      This page allows to change order of Metadata Fields for a repository and
      change some metadata field to viewOnly or Study.
    </p>
    <p>
      Note: content type is the level at which the metadata field is assigned
      (image, repository/ImageSet, folder/case)<br />
      Note: You can directly use check box to change viewOnly or Study status of
      metadata fields. An metadata field is either in viewOnly or in Study or in
      editing (normal) mode.
    </p>

    <!-- Get Repository id from user -->
    <form action="{{ url_for('orderviewonly.updatetable') }}" method="POST">
      <div id="horizontal-button-container">
        <label for="source_repository_id">Enter Source Repository ID: </label>
        <input
          type="text"
          id="source_repository_id"
          name="source_repository_id"
          required
          value="{{repository_id}}"
        />
        <input type="submit" value="Load Image fields" name="loadImageField" />
        <input
          type="submit"
          value="Load Folder Fields"
          name="loadFolderField"
        />
        <input
          type="submit"
          value="Load ImageSet Fields"
          name="loadImageSetField"
        />
      </div>
    </form>

    <!-- Setting button (hidden for now)-->
    <div class="dropdown-container" style="display: none">
      <button class="settings-button" onclick="goToSettings()">⚙️</button>
    </div>

    <!-- Return button -->
    <div class="return-container">
      <button onclick="window.location.href='/main';">Main Menu</button>
    </div>

    <!-- Status indicator (to show flash message) -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <div class="flash-msg">
      {% for category, msg in messages %}
      <div class="{{ category }}">{{ msg }}</div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %}

    <!-- Metadata Fields Table (hidden by default) -->
    <div id="table-container">
      {% if repository_text %}
      <h1>Metadata Fields {{repository_text}}</h1>
      {% endif %} {% if metadata_fields %}
      <table id="table">
        <thead>
          <tr>
            <th>checkbox</th>
            <th>ID</th>
            <th>Name</th>
            <th>Content Type</th>
            <th>Order</th>
            <th>ViewOnly</th>
            <th>Study</th>
          </tr>
        </thead>
        <tbody>
          {% for metadata_field in metadata_fields %}
          <tr>
            <td>
              <input
                type="checkbox"
                name="selected_metadata_field"
                value="{{ metadata_field.id }}"
              />
            </td>
            <td>{{ metadata_field.id }}</td>
            <td>{{ metadata_field.name }}</td>
            <td>{{ metadata_field.content_type }}</td>
            <td>{{ metadata_field.order }}</td>

            <td>
              <input
                type="checkbox"
                name="viewonly"
                value="{{ metadata_field.id }}"
                {%
                if
                metadata_field.viewonly
                %}
                checked
                {%
                endif
                %}
                onchange="UpdateViewOnly(this)"
              />
            </td>

            <td>
              <input
                type="checkbox"
                name="study"
                value="{{ metadata_field.id }}"
                {%
                if
                metadata_field.study
                %}
                checked
                {%
                endif
                %}
                onchange="UpdateStudy(this)"
              />
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>Any images loaded yet.</p>
      {% endif %}
    </div>

    {% if repository_text %}
    <h1>Order and ViewOnly modification buttons</h1>
    {% endif %}

    <!-- Templates Order changes (hidden by default) -->
    {% if repository_text %}
    <div>
      Enter order of field id (image level only): <br />
      This will set metadata field of image type in the specified order. If a
      field is not contained in the repository, it will be skipped. Other fields
      are placed after all these fields (but keeping its original order).
      <form
        action="{{ url_for('orderviewonly.OrderTemplateUpdate') }}"
        method="POST"
        onsubmit="return get_repo_id('hiddenrepoid3')"
      >
        <input
          type="text"
          name="templates_field_ids"
          value="29, 30, 31, 32, 33, 80, 34, 36, 37, 38, 39, 40, 41, 42, 44, 45, 76, 35"
        />
        <input type="hidden" id="hiddenrepoid3" name="hiddenrepoid3" />
        <input
          type="submit"
          value="TemplateOrderUpdate"
          name="TemplateOrderUpdate"
        />
      </form>
    </div>
    {% endif %}

    <!-- eSM order change button (hidden by default) -->

    <div class="single-button">
      <form
        action="{{ url_for('orderviewonly.esmOrderUpdate') }}"
        method="POST"
        onsubmit="return get_repo_id('hiddenrepoid1')"
      >
        <div id="horizontal-button-container">
          <p>
            {% if repository_text %} This button will place all "eSM" containing
            metadata field at the end of order (for all content type):
          </p>
          <input type="hidden" id="hiddenrepoid1" name="hiddenrepoid1" />
          <input type="submit" value="esmOrderUpdate" name="esmOrderUpdate" />
        </div>
      </form>
    </div>
    {% endif %}

    <!-- eSM viewonly change button (hidden by default) -->

    <div class="single-button">
      <form
        action="{{ url_for('orderviewonly.esmViewOnlyUpdate') }}"
        method="POST"
        onsubmit="return get_repo_id('hiddenrepoid2')"
      >
        <div id="horizontal-button-container">
          <p>
            {% if repository_text %} This button will place all "eSM" containing
            metadata field to viewOnly (for all content type):
          </p>
          <input type="hidden" id="hiddenrepoid2" name="hiddenrepoid2" />
          <input
            type="submit"
            value="esmViewOnlyUpdate"
            name="esmViewOnlyUpdate"
          />
        </div>
      </form>
    </div>
    {% endif %}
  </body>

  <script>
    function get_repo_id(targetId) {
      try {
        var input1Value = document.getElementById("source_repository_id").value;
        document.getElementById(targetId).value = input1Value;
        return true; // Allow the form submission to proceed
      } catch (error) {
        console.error("An error occurred:", error);
        return false; // Prevent form submission on error
      }
    }

    function UpdateViewOnly(element) {
      fetch("/orderviewonly/UpdateViewOnly", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          repository_id: document.getElementById("source_repository_id").value,
          metadata_field_id: element.value,
          checkbox_checked: element.checked,
        }),
      })
        .then((response) => response.text())
        .then((html) => {
          document.body.innerHTML = html;
        })
        .catch((error) => {
          console.error("Error:", error);
        });
    }

    function UpdateStudy(element) {
      fetch("/orderviewonly/UpdateStudy", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          repository_id: document.getElementById("source_repository_id").value,
          metadata_field_id: element.value,
          checkbox_checked: element.checked,
        }),
      })
        .then((response) => response.text())
        .then((html) => {
          document.body.innerHTML = html;
        })
        .catch((error) => {
          console.error("Error:", error);
        });
    }
  </script>
</html>